---
- hosts: all
  become: true
  pre_tasks:

  - name: install updates (Ubuntu)
    tags: always
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: install updates (CentOS)
    tags: always
    dnf:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "CentOS"

- hosts: web_servers
  become: true
  tasks:

  - name: Installing docker in Ubuntu
    apt:
      name:
        - docker.io
      state: latest
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

- hosts: db_servers
  become: true
  tasks:

  - name: Installing docker in CentOS
    dnf:
      name:
        - docker
      state: latest
    when: ansible_distribution == "CentOS"


